# ======================================================================
# Hyprland Main Config
# ======================================================================
# ======================================================================
# Config includes (Hyprland 0.52.2 syntax)
# ======================================================================
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/machine/monitors.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/configs/plugins.conf
source = ~/.config/hypr/theme/theme.conf

# ======================================================================
# Autostart
# ======================================================================
exec-once = swaync
exec-once = ~/.config/wayscripts/swaync-autoopen.sh &
#exec-once = ~/.config/hypr/scripts/hotplug/reload-hyprpaper.sh
exec-once = eww daemon
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = swww-daemon
exec-once = sleep 2 && swww img /home/mads/Pictures/wallpapers/terpinedream.png

#exec-once = ~/.config/hypr/scripts/autostart/services
#exec-once = ~/.config/hypr/scripts/autostart/apps
# ======================================================================
# Execs
# ======================================================================
#exec = ~/.config/wayscripts/bt-monitor.sh &
#exec = ~/.config/wayscripts/nm-monitor.sh &
#exec = ~/.config/wayscripts/battery-monitor.sh &

# ======================================================================
# Waybar layer rules
# ======================================================================
#layerrule = noanim, waybar
#layerrule = blur, waybar
#layerrule = ignorealpha 0.5, waybar

# ======================================================================
# General Options
# ======================================================================
general {
    resize_on_border = true
}
