#!/bin/bash

# Apps
feishin &

# Terminal Apps
# kitty --class btop btop &
# kitty --class nvtop nvtop &
# Wallpaper
#hyprpaper &

# System tray + bar
#waybar &
#swaync &

# Ghostty terminal
ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &
