# Custom colors matching fastfetch (darker to blend with wallpaper)
foreground            #B4BEFE
background            #0F0F14

# Cursor
cursor                #EBC0EC

# Selection
selection_foreground  #0F0F14
selection_background  #CBA6F7

# Main accents
color0   #0F0F14
color1   #FAB387
color2   #CBA6F7
color3   #EBC0EC
color4   #B4BEFE
color5   #CBA6F7
color6   #EBC0EC
color7   #FAB387

color8   #0F0F14
color9   #FAB387
color10  #CBA6F7
color11  #EBC0EC
color12  #B4BEFE
color13  #CBA6F7
color14  #EBC0EC
color15  #FAB387
